-- ============================================================
-- SUPERSEDED — do not run.
--
-- This file originally added all the Swan & Dolphin dining to the
-- Dolphin. That was wrong: the venues are split across three buildings
-- (Swan, Dolphin, Swan Reserve). Use instead:
--
--     swan_dolphin_dining_2026_07.sql
--
-- which places each venue in its correct building and also cleans up
-- anything this file may have added to the Dolphin.
-- ============================================================
