-- ═══════════════════════════════════════════════════════════════════
-- RESORTS — Phase 2 activities (July 2026)
-- Seeds every resort with standard trackable activities. Run once.
-- Run AFTER resorts_phase1_2026_07.sql.
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO experiences (name, park, category, type, description, duration, is_active, sort_name, location) VALUES
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Grand Floridian'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Grand Floridian'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Grand Floridian'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Grand Floridian'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Polynesian'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Polynesian'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Polynesian'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Polynesian'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Contemporary'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Contemporary'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Contemporary'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Contemporary'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Wilderness Lodge'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Wilderness Lodge'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Wilderness Lodge'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Wilderness Lodge'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Animal Kingdom Lodge'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Animal Kingdom Lodge'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Animal Kingdom Lodge'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Animal Kingdom Lodge'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Beach Club'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Beach Club'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Beach Club'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Beach Club'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Yacht Club'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Yacht Club'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Yacht Club'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Yacht Club'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'BoardWalk Inn'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'BoardWalk Inn'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'BoardWalk Inn'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'BoardWalk Inn'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Riviera'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Riviera'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Riviera'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Riviera'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Caribbean Beach'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Caribbean Beach'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Caribbean Beach'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Caribbean Beach'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Coronado Springs'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Coronado Springs'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Coronado Springs'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Coronado Springs'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Port Orleans French Quarter'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Port Orleans French Quarter'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Port Orleans French Quarter'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Port Orleans French Quarter'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Port Orleans Riverside'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Port Orleans Riverside'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Port Orleans Riverside'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Port Orleans Riverside'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Fort Wilderness'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Fort Wilderness'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Fort Wilderness'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Fort Wilderness'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Pop Century'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Pop Century'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Pop Century'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Pop Century'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Art of Animation'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Art of Animation'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Art of Animation'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Art of Animation'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'All-Star Movies'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'All-Star Movies'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'All-Star Movies'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'All-Star Movies'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'All-Star Music'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'All-Star Music'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'All-Star Music'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'All-Star Music'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'All-Star Sports'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'All-Star Sports'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'All-Star Sports'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'All-Star Sports'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Old Key West'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Old Key West'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Old Key West'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Old Key West'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Saratoga Springs'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Saratoga Springs'),
('Arcade', 'Resorts', 'Attractions', 'Arcade', 'Play games at the resort''s arcade.', 'Varies', true, 'Arcade', 'Saratoga Springs'),
('Movie under the stars', 'Resorts', 'Entertainment', 'Outdoor Movie', 'Watch a Disney film outdoors under the stars at the resort.', '90 min', true, 'Movie under the stars', 'Saratoga Springs'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Swan'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Swan'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Dolphin'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Dolphin'),
('Overnight stay', 'Resorts', 'Events & Tours', 'Stay', 'Book a stay and spend the night at this resort, surrounded by its theming.', '1 night', true, 'Overnight stay', 'Swan Reserve'),
('Resort pool', 'Resorts', 'Attractions', 'Pool', 'Take a dip in the resort''s themed feature pool.', 'Varies', true, 'Resort pool', 'Swan Reserve');

-- 90 activities across 24 resorts
